### ISSUE TITLE
Сообщение в логах Z2M после обновления девайса...

### ISSUE THREAD

**Issue by Nikolay-Ch** [slacky1965/tuya_thermostat_zrd#39]
После обновления и переинтервьюирования я получил такую строчку в логе:
`zh:controller:device: Device '0xXXXXXXXXXXXXXX' is only compliant to revision '21' of the ZigBee specification (current revision: 23).`

Устройство при этом работает и в Z2M и в ХА...

**Comment by slacky1965** [comment]
Видимо это от координатора зависит. У меня нет таких сообщений. Но на самом деле это не страшно. На 21 ревизии все продолжает работать. Ну просто у Телинка пока вот так в SDK. В логе просто предупрежедние, что текущая 23, а используется 21.
